spring:
  application:
    name: coupon-eureka

server:
  port: 8000

eureka:
  client:
    fetch-registry: false          #是否从Eureka Server获取注册信息，不需要同步其他节点的数据，设置为false
    register-with-eureka: false    #是否将自己注册代Eureka Server，由于当前应用是单节点，所以为false
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/